on: [push]

jobs:
  setup_bazel_test:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup bazel
      uses: ./
      id: setup
      with:
        bazel-version: '2.0.0'

    - name: Run bazel --version
      run: bazel --version

    - name: Install
      run: npm install

    - name: Format
      run: |
        npm run format
        git diff --quiet

    - name: Run tests
      run: npm test
